#!/bin/bash
# 1.-Descarga

#.-Acceso directo
sudo ln -s /opt/odoo//account_export_csv,
sudo ln -s /opt/odoo//account_move_line_report_xls,
sudo ln -s /opt/odoo//account_chart_update ,
sudo ln -s /opt/odoo//account_invoice_constraint_chronology,
sudo ln -s /opt/odoo//account_invoice_currency, 
sudo ln -s /opt/odoo//account_journal_always_check_date,
sudo ln -s /opt/odoo//account_renumber,
sudo ln -s /opt/odoo//account_due_list,
sudo ln -s /opt/odoo//account_due_list_payment_mode,
sudo ln -s /opt/odoo//account_banking_mandate, 
sudo ln -s /opt/odoo//account_banking_pain_base,
sudo ln -s /opt/odoo//account_banking_payment_export,
sudo ln -s /opt/odoo//account_banking_payment_transfer,
sudo ln -s /opt/odoo//account_banking_sepa_direct_debit,
sudo ln -s /opt/odoo//account_direct_debit,
sudo ln -s /opt/odoo//account_payment_partner,
sudo ln -s /opt/odoo//account_bank_statement_import, NO EXISTE EN LA 10
sudo ln -s /opt/odoo//attachment_preview,
sudo ln -s /opt/odoo//attachments_to_filesystem,
sudo ln -s /opt/odoo//document_page,
sudo ln -s /opt/odoo//document_url,
sudo ln -s /opt/odoo//account_balance_reporting_xls,
sudo ln -s /opt/odoo//account_balance_reporting,
sudo ln -s /opt/odoo//account_refund_original,
sudo ln -s /opt/odoo//l10n_es_account_asset,
sudo ln -s /opt/odoo//l10n_es_account_balance_report,
sudo ln -s /opt/odoo//l10n_es_account_bank_statement_import_n43,
sudo ln -s /opt/odoo//l10n_es_account_invoice_sequence,
sudo ln -s /opt/odoo//sudo ln -s /opt/odoo//l10n_es_aeat_mod111,
sudo ln -s /opt/odoo//l10n_es_aeat_mod115,
sudo ln -s /opt/odoo//l10n_es_aeat_mod130,
sudo ln -s /opt/odoo//l10n_es_aeat_mod303,
sudo ln -s /opt/odoo//l10n_es_aeat_mod340_type0,
sudo ln -s /opt/odoo//l10n_es_aeat_mod340,
sudo ln -s /opt/odoo//l10n_es_aeat_mod347,
sudo ln -s /opt/odoo//l10n_es_aeat_mod349,
sudo ln -s /opt/odoo//l10n_es_aeat,
sudo ln -s /opt/odoo//l10n_es_fiscal_year_closing,
sudo ln -s /opt/odoo//l10n_es_partner_mercantil,
sudo ln -s /opt/odoo//l10n_es_partner,
sudo ln -s /opt/odoo//l10n_es_pos,
sudo ln -s /opt/odoo//l10n_es_toponyms,
sudo ln -s /opt/odoo//l10n_es,
sudo ln -s /opt/odoo//base_location,
sudo ln -s /opt/odoo//base_location_geonames_import,
sudo ln -s /opt/odoo//base_partner_sequence,
sudo ln -s /opt/odoo//report_custom_filename,
sudo ln -s /opt/odoo//report_xls,
sudo ln -s /opt/odoo//disable_openerp_online,
sudo ln -s /opt/odoo//mass_editing,
sudo ln -s /opt/odoo//web_export_view



